/**
 * QR type detection and file decode utilities.
 *
 * Used by: src/app/(main)/scan/page.tsx
 * SSR-safe: no top-level browser API imports
 */

/** Matches wallet IDs generated by the receive-qr page (e.g. W-123456) */
export const P2P_WALLET_REGEX = /^W-\d{6,}$/

/** Discriminated union of recognised QR content types */
export type QRType =
  | { type: 'p2p_wallet'; walletId: string }
  | { type: 'unknown'; rawValue: string }

/**
 * Pure function — determines the routing type of a decoded QR string.
 *
 * @param rawValue - The raw decoded string from the QR code
 * @returns A typed QRType discriminated union
 */
export function detectQRType(rawValue: string): QRType {
  const trimmed = rawValue.trim()
  if (P2P_WALLET_REGEX.test(trimmed)) {
    return { type: 'p2p_wallet', walletId: trimmed }
  }
  return { type: 'unknown', rawValue: trimmed }
}

/**
 * Decodes a QR code from an image file using the BarcodeDetector API.
 * Falls back to a dynamic polyfill import if the native API is unavailable.
 *
 * SSR-safe: only called from client-side event handlers.
 *
 * @param file - An image File object selected from the gallery
 * @returns The decoded QR string, or null if no QR code was found or an error occurred
 */
export async function decodeQRFromFile(file: File): Promise<string | null> {
  try {
    if (typeof window !== 'undefined' && !('BarcodeDetector' in window)) {
      const { BarcodeDetector: BDPoly } = await import('barcode-detector/pure')
      // @ts-expect-error -- polyfill global assignment; BarcodeDetector not in TS lib types
      window.BarcodeDetector = BDPoly
    }

    const detector = new BarcodeDetector({ formats: ['qr_code'] })
    const bitmap = await createImageBitmap(file)
    const results = await detector.detect(bitmap)
    return results[0]?.rawValue ?? null
  } catch {
    return null
  }
}
